### ISSUE TITLE
CHT - ChatListFragment - QA - The app is stopped abruptly

### ISSUE THREAD

**Issue by darkestpriest** [bitDubai/fermat#4707]
When I press two times a contact element in Contact Fragment the app is stopped and throws this exception in logcat:
`02-06 20:38:38.541 1852-1852/com.bitdubai.fermat E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.bitdubai.fermat, PID: 1852
                                                                   java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131624521, class android.widget.ListView) with Adapter(class com.bitbudai.fermat_cht_android_sub_app_chat_bitdubai.adapters.ContactListAdapter)]
                                                                       at android.widget.ListView.layoutChildren(ListView.java:1562)
                                                                       at android.widget.AbsListView$CheckForTap.run(AbsListView.java:3281)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by darkestpriest** [comment]
Fixed
